In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sample_transations.csv")

In [3]:
del df['Unnamed: 0']

In [4]:
df.head()

,dd_card_number,store_number,dd_transaction_number,sku,quantity,post_discount_price,date,hour,dbi_item_catgry,dbi_item_sub_catgry,dbi_item_famly_name,dbi_item_size
0,0,775,7969,74,1,2.29,9/2/2015,Lunch,Beverages,Hot Coffee,Hot Coffee,Large
1,0,775,7969,73,1,0.00,9/2/2015,Lunch,Beverages,Hot Coffee,Hot Coffee,Medium
2,0,761,16021,75,1,2.49,9/4/2015,Morning,Beverages,Hot Coffee,Hot Coffee,X-Large
3,0,761,16021,50,1,2.49,9/4/2015,Morning,Beverages,Hot Coffee,Hot Coffee,X-Large
4,0,761,16021,50,1,0.00,9/4/2015,Morning,Beverages,Hot Coffee,Hot Coffee,X-Large

In [5]:
df = df.join(pd.get_dummies(df['hour']))
df = df.join(pd.get_dummies(df['dbi_item_catgry'], prefix='catgry'))
df = df.join(pd.get_dummies(df['dbi_item_sub_catgry'], prefix='sub_catgry'))
df = df.join(pd.get_dummies(df['dbi_item_famly_name'], prefix='famly_name'))
df = df.join(pd.get_dummies(df['dbi_item_size'], prefix='size'))

In [6]:
median_price_size = df.groupby('dbi_item_size')['post_discount_price'].median().reset_index()
df = df.merge(median_price_size, on='dbi_item_size', suffixes=("", 'median_price_per_size'))
df

,dd_card_number,store_number,dd_transaction_number,sku,quantity,post_discount_price,date,hour,dbi_item_catgry,dbi_item_sub_catgry,...,size_Texas Toast,size_Turbo Shot,size_Twist,size_Veggie,size_Waffle,size_Water,size_Wrap,size_X-Large,size_X-Small,post_discount_pricemedian_price_per_size
0,0,775,7969,74,1,2.29,9/2/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
1,0,761,16048,74,2,4.58,9/6/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
2,0,761,16054,74,1,2.29,9/7/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
3,0,775,8041,49,1,2.29,9/9/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
4,0,775,8041,74,1,2.29,9/9/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
5,0,761,16088,49,1,2.29,9/11/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
6,0,761,16105,49,1,2.14,9/13/2015,Afternoon,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
7,0,761,16132,74,1,2.03,9/16/2015,Morning,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
8,0,505,1989,74,3,6.07,9/20/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
9,0,775,8206,74,1,2.29,9/23/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
10,0,761,16226,74,1,1.96,9/26/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
11,0,761,16226,74,1,2.10,9/26/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
12,0,761,16238,74,1,2.29,9/27/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
13,0,761,16238,74,1,2.29,9/27/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
14,0,775,8287,74,1,2.29,9/30/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
15,0,761,16292,74,1,2.29,10/3/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
16,0,761,16292,74,1,2.29,10/3/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
17,0,761,16292,49,1,2.29,10/3/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
18,0,775,8334,74,3,6.87,10/4/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
19,0,775,8376,74,1,2.29,10/7/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
20,0,761,16357,74,1,2.29,10/10/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
21,0,761,16357,74,1,2.29,10/10/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
22,0,761,16362,74,1,2.29,10/11/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
23,0,761,16362,74,1,2.29,10/11/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
24,0,761,16426,74,2,4.58,10/17/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
25,0,761,16435,74,1,2.29,10/18/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
26,0,761,16435,74,1,2.29,10/18/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
27,0,761,16458,74,1,2.29,10/21/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
28,0,761,16475,74,2,4.08,10/23/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
29,0,761,16481,74,2,4.08,10/24/2015,Lunch,Beverages,Hot Coffee,...,0,0,0,0,0,0,0,0,0,2.290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51909,44,1278,3547,98,1,1.61,12/5/2015,Lunch,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,1.865
51910,54,658,16808,98,1,1.61,9/24/2015,Afternoon,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,1.865
51911,54,1431,140,98,1,1.98,10/7/2015,Afternoon,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,1.865
51912,54,891,22925,98,1,1.80,11/6/2015,Afternoon,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,1.865
51913,54,1044,20845,98,1,1.93,2/7/2016,Afternoon,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,1.865
51914,54,664,20951,98,1,2.12,2/9/2016,Lunch,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,1.865
51915,44,1278,3741,113,1,11.99,2/16/2016,Morning,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,11.990
51916,44,1278,3870,113,1,11.99,4/1/2016,Morning,Food - Bakery,Donut Varieties,...,0,0,0,0,0,0,0,0,0,11.990
51917,45,850,16672,564,1,11.99,1/30/2016,Morning,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,11.990
51918,46,1012,16696,521,1,3.49,8/28/2016,Lunch,Food PM,"Turkey, Cheddar & Bacon Sandwich",...,0,0,0,0,0,0,0,0,0,3.490
51919,49,1416,3311,606,1,2.19,3/31/2016,Morning,Food AM,Kolache,...,0,0,0,0,0,0,0,0,0,2.190
51920,51,1318,3521,171,1,17.98,9/30/2015,Lunch,Food - Bakery,Bagels,...,0,0,0,0,0,0,0,0,0,17.980
51921,51,1318,3521,44,2,5.98,9/30/2015,Lunch,Food - Bakery,Bagels,...,0,0,0,0,0,0,0,0,0,5.980
51922,65,543,22363,44,1,3.99,11/13/2015,Morning,Food - Bakery,Bagels,...,0,0,0,0,0,0,0,0,0,5.980
51923,68,5,12734,44,3,8.67,5/10/2016,Morning,Food - Bakery,Bagels,...,0,0,0,0,0,0,0,0,0,5.980
51924,53,84,8281,473,1,19.99,9/20/2015,Lunch,Other,Packaged Coffee,...,0,0,0,0,0,0,0,0,0,19.990
51925,54,658,16973,473,1,19.99,10/18/2015,Afternoon,Other,Packaged Coffee,...,0,0,0,0,0,0,0,0,0,19.990
51926,55,1374,2991,570,1,1.99,7/30/2016,Morning,Food - Bakery,Oatmeal,...,0,0,0,0,0,0,0,0,0,1.990
51927,56,903,7587,527,1,3.99,11/7/2015,Morning,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,3.990
51928,56,903,7587,528,1,3.99,11/7/2015,Morning,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,3.990
51929,89,1082,16247,603,2,7.98,6/10/2016,Lunch,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,3.990
51930,58,725,22641,97,1,9.99,2/20/2016,Morning,Food - Bakery,Bagels,...,0,0,0,0,0,0,0,0,0,9.990
51931,68,5,12734,97,1,9.99,5/10/2016,Morning,Food - Bakery,Bagels,...,0,0,0,0,0,0,0,0,0,9.990
51932,60,276,21087,153,1,0.99,8/10/2016,Night,Food PM,Soft Serve,...,0,0,0,0,0,0,0,0,0,0.990
51933,64,864,7441,586,1,2.99,11/9/2015,Morning,Food PM,Grilled Cheese Sandwich,...,0,0,0,0,0,0,0,0,0,2.990
51934,65,1461,1795,286,1,0.50,6/7/2016,Morning,Food - Bakery,Oatmeal,...,0,0,0,0,0,0,0,0,0,0.500
51935,66,1111,5370,245,1,0.59,10/1/2015,Morning,Other,Gum,...,0,0,0,0,0,0,0,0,0,0.590
51936,72,252,16960,559,1,11.99,12/13/2015,Morning,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,11.990
51937,83,254,9361,496,1,5.99,8/12/2016,Lunch,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,8.385
51938,95,1189,4629,562,2,10.78,11/23/2015,Lunch,Other,Retail Merchandise,...,0,0,0,0,0,0,0,0,0,8.385

In [7]:
median_price_person = df.groupby('dd_card_number')['post_discount_price'].median()
df = df.merge(median_price_person, on='dd_card_number', suffixes=("", 'median_price_per_person'))

In [8]:
median_price_store = df.groupby('store_number')['post_discount_price'].median()
df = df.merge(median_price_store, on='store_number', suffixes=("", 'median_price_per_store'))

In [9]:
median_price_store_on_sum = df.groupby('store_number')['post_discount_price'].median() /  df.groupby('store_number')['post_discount_price'].sum()
df = df.merge(median_price_store_on_sum, on='store_number', suffixes=("", 'median_price_store_on_sum'))

In [10]:
median_price_person_on_sum = df.groupby('dd_card_number')['post_discount_price'].median() /  df.groupby('dd_card_number')['post_discount_price'].sum()
df = df.merge(median_price_person_on_sum, on='dd_card_number', suffixes=("", 'median_price_person_on_sum'))

In [11]:
median_price_person_per_day = df.groupby(['dd_card_number','date'])['post_discount_price'].median().reset_index()
df = df.merge(median_price_person_per_day, on=['dd_card_number','date'], suffixes=("", 'median_price_person_per_day'))

In [15]:
df

,dd_card_number,store_number,dd_transaction_number,sku,quantity,post_discount_price,date,Afternoon,Lunch,Morning,...,size_Water,size_Wrap,size_X-Large,size_X-Small,post_discount_pricemedian_price_per_size,post_discount_pricemedian_price_per_person,post_discount_pricemedian_price_per_store,post_discount_pricemedian_price_store_on_sum,post_discount_pricemedian_price_person_on_sum,post_discount_pricemedian_price_person_per_day
0,0,775,7969,74,1,2.29,9/2/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,1.145
1,0,775,7969,73,1,0.00,9/2/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.059807,0.002263,1.145
2,0,775,8041,49,1,2.29,9/9/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.290
3,0,775,8041,74,1,2.29,9/9/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.290
4,0,775,8041,48,1,0.00,9/9/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.059807,0.002263,2.290
5,0,775,8206,74,1,2.29,9/23/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.190
6,0,775,8206,73,1,2.09,9/23/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.059807,0.002263,2.190
7,0,775,8287,74,1,2.29,9/30/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.190
8,0,775,8287,73,1,2.09,9/30/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.059807,0.002263,2.190
9,0,775,8334,74,3,6.87,10/4/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,4.360
10,0,775,8334,72,1,1.85,10/4/2015,0,1,0,...,0,0,0,0,1.79,2.29,2.290,0.059807,0.002263,4.360
11,0,775,8376,74,1,2.29,10/7/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.190
12,0,775,8376,73,1,2.09,10/7/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.059807,0.002263,2.190
13,0,775,8943,49,1,2.29,11/25/2015,0,0,1,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.290
14,0,775,8943,74,1,2.29,11/25/2015,0,0,1,...,0,0,0,0,2.29,2.29,2.290,0.059807,0.002263,2.290
15,0,775,10710,75,1,2.49,6/3/2016,0,1,0,...,0,0,1,0,2.48,2.29,2.290,0.059807,0.002263,1.245
16,0,775,10710,75,1,2.49,6/3/2016,0,1,0,...,0,0,1,0,2.48,2.29,2.290,0.059807,0.002263,1.245
17,0,775,10710,111,1,0.00,6/3/2016,0,1,0,...,0,0,0,0,0.99,2.29,2.290,0.059807,0.002263,1.245
18,0,775,10710,111,1,0.00,6/3/2016,0,1,0,...,0,0,0,0,0.99,2.29,2.290,0.059807,0.002263,1.245
19,0,761,16048,74,2,4.58,9/6/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.005225,0.002263,3.215
20,0,761,16048,72,1,1.85,9/6/2015,0,1,0,...,0,0,0,0,1.79,2.29,2.290,0.005225,0.002263,3.215
21,0,761,16054,74,1,2.29,9/7/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.005225,0.002263,2.290
22,0,761,16088,49,1,2.29,9/11/2015,0,1,0,...,0,0,0,0,2.29,2.29,2.290,0.005225,0.002263,2.090
23,0,761,16088,73,1,2.09,9/11/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.005225,0.002263,2.090
24,0,761,16088,73,1,2.09,9/11/2015,0,1,0,...,0,0,0,0,1.99,2.29,2.290,0.005225,0.002263,2.090
25,0,761,16105,49,1,2.14,9/13/2015,1,0,0,...,0,0,0,0,2.29,2.29,2.290,0.005225,0.002263,1.550
26,0,761,16105,103,1,1.55,9/13/2015,1,0,0,...,0,0,0,0,1.41,2.29,2.290,0.005225,0.002263,1.550
27,0,761,16105,184,1,0.00,9/13/2015,1,0,0,...,0,0,0,0,1.41,2.29,2.290,0.005225,0.002263,1.550
28,0,761,16132,74,1,2.03,9/16/2015,0,0,1,...,0,0,0,0,2.29,2.29,2.290,0.005225,0.002263,1.940
29,0,761,16132,48,1,1.85,9/16/2015,0,0,1,...,0,0,0,0,1.99,2.29,2.290,0.005225,0.002263,1.940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51909,97,517,14124,619,1,1.79,7/17/2016,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,2.390
51910,97,517,14142,169,1,2.99,7/20/2016,0,1,0,...,0,0,0,0,1.99,1.59,1.990,0.042322,0.001874,1.490
51911,97,517,14142,418,1,1.99,7/20/2016,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,1.490
51912,97,517,14142,178,1,1.49,7/20/2016,0,1,0,...,0,0,0,0,2.19,1.59,1.990,0.042322,0.001874,1.490
51913,97,517,14142,180,1,0.00,7/20/2016,0,1,0,...,0,0,0,0,0.00,1.59,1.990,0.042322,0.001874,1.490
51914,97,517,14142,81,1,0.95,7/20/2016,0,1,0,...,0,0,0,0,1.29,1.59,1.990,0.042322,0.001874,1.490
51915,97,517,12402,418,1,2.99,9/2/2015,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,2.370
51916,97,517,12402,79,1,1.75,9/2/2015,0,1,0,...,0,0,0,0,1.59,1.59,1.990,0.042322,0.001874,2.370
51917,97,517,12535,418,1,2.99,9/28/2015,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,1.970
51918,97,517,12535,81,1,0.95,9/28/2015,0,1,0,...,0,0,0,0,1.29,1.59,1.990,0.042322,0.001874,1.970
51919,97,517,12564,418,1,2.99,10/3/2015,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,1.970
51920,97,517,12564,81,1,0.95,10/3/2015,0,1,0,...,0,0,0,0,1.29,1.59,1.990,0.042322,0.001874,1.970
51921,97,517,13599,418,1,2.99,4/27/2016,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,1.970
51922,97,517,13599,81,1,0.95,4/27/2016,0,1,0,...,0,0,0,0,1.29,1.59,1.990,0.042322,0.001874,1.970
51923,97,517,14326,418,1,3.29,8/23/2016,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,3.290
51924,97,517,14326,100,1,6.49,8/23/2016,0,1,0,...,0,0,0,0,5.49,1.59,1.990,0.042322,0.001874,3.290
51925,97,517,14326,81,1,0.95,8/23/2016,0,1,0,...,0,0,0,0,1.29,1.59,1.990,0.042322,0.001874,3.290
51926,97,517,14346,418,1,3.29,8/27/2016,0,1,0,...,0,0,0,0,1.79,1.59,1.990,0.042322,0.001874,3.290
51927,97,129,247,418,1,2.99,9/10/2015,0,1,0,...,0,0,0,0,1.79,1.59,2.190,0.130981,0.001874,2.190
51928,97,129,247,79,1,1.39,9/10/2015,0,1,0,...,0,0,0,0,1.59,1.59,2.190,0.130981,0.001874,2.190
51929,97,129,292,418,1,2.99,9/17/2015,0,1,0,...,0,0,0,0,1.79,1.59,2.190,0.130981,0.001874,2.190
51930,97,129,292,79,1,1.39,9/17/2015,0,1,0,...,0,0,0,0,1.59,1.59,2.190,0.130981,0.001874,2.190
51931,97,129,320,418,1,2.99,9/22/2015,0,1,0,...,0,0,0,0,1.79,1.59,2.190,0.130981,0.001874,1.990
51932,97,129,320,81,1,0.99,9/22/2015,0,1,0,...,0,0,0,0,1.29,1.59,2.190,0.130981,0.001874,1.990
51933,97,129,377,418,1,2.99,10/1/2015,0,1,0,...,0,0,0,0,1.79,1.59,2.190,0.130981,0.001874,1.990
51934,97,129,377,81,1,0.99,10/1/2015,0,1,0,...,0,0,0,0,1.29,1.59,2.190,0.130981,0.001874,1.990
51935,97,167,12958,418,3,8.97,2/6/2016,0,1,0,...,0,0,0,0,1.79,1.59,3.085,0.188225,0.001874,3.085
51936,97,167,12958,271,2,2.58,2/6/2016,0,1,0,...,0,1,0,0,1.69,1.59,3.085,0.188225,0.001874,3.085
51937,97,167,12958,111,1,1.25,2/6/2016,0,1,0,...,0,0,0,0,0.99,1.59,3.085,0.188225,0.001874,3.085
51938,97,167,12958,247,1,3.59,2/6/2016,0,1,0,...,0,0,0,0,3.29,1.59,3.085,0.188225,0.001874,3.085

In [14]:
del df['hour']
del df['dbi_item_catgry']
del df['dbi_item_sub_catgry']
del df['dbi_item_famly_name']
del df['dbi_item_size']

In [23]:
df['Date'] = pd.to_datetime(df['date'], format='%m/%d/%Y') 
df['year'] = df['Date'].dt.year
df['week'] = df['Date'].dt.week
df['day'] = df['Date'].dt.day
del df['date']
del df['Date']

In [27]:
len(df)

51939

In [30]:
df = df.dropna()

In [31]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

ns = list(range(2, 20, 1))
plt.plot(ns, [KMeans(n_clusters=n).fit(df).score(df) for n in ns]);

KeyboardInterrupt: